### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jshipton** [jcorbino/mole#8]
[https://github.com/openjournals/joss-reviews/issues/3380](url) It would be great to have installation instructions for Mac users e.g. `brew install superlu`. I'd add them myself but I'm trying to avoid upgrading my OS as I'm going to buy a new laptop soon so anything I do may well be out of date!

**Comment by jcorbino** [comment]
I agree with you @jshipton, don't worry I'll add them!

Please let me know if there's something else 👍🏻

**Comment by jshipton** [comment]
Thanks! My other question is have you ever installed on an HPC cluster? That's the other option I have for installing and testing the code...

**Comment by jcorbino** [comment]
As a matter of fact, I have done it, but it was mainly to test the parallel LU decomposition via SuperLU_Dist in a couple of problems. That I remember, I pretty much followed the same steps EXCEPT that since I didn't have root privileges, I had to locally build and link against SuperLU. What I can do is to add the instructions for Mac users between today and tomorrow (since I'm a bit busy today) so you can try it on your laptop, would that work for you @jshipton?

**Comment by jshipton** [comment]
That sounds like a good plan! I have tried a few things myself but have not made it work yet. I'm afraid I'm on holiday for the next 2 weeks so I will complete as much of the rest of the review as I can but I'm not sure how far I'll get with installing...

**Comment by jshipton** [comment]
Hi @jcorbino! Any progress on the Mac installation instructions?

**Comment by jcorbino** [comment]
Hi @jshipton I'm so sorry for the delay with the instructions for Mac users. I just wanted to let you know that tomorrow (Wednesday, October 6th) I'll push the updated "README" file with a section explaining the steps for MacOS. Basically the best way to go is by installing Eigen instead of SuperLU. But of course, there are a couple of flags that must be changed in MOLE'S Makefile for it to work on a Mac. Tomorrow I'll let you know.

Thank you,

**Comment by jcorbino** [comment]
Here you go @jshipton

https://www.dropbox.com/s/0u7x9rrqy1onvst/MOLE%20installation%20on%20MacOS.pdf?dl=0

Thanks,
